### ISSUE TITLE
Any chances of CAVE SH3 driver being backported to this version?

### ISSUE THREAD

**Issue by joshsmithtogo** [arcadez/-mame2003-plus-libretro#4]
Don't know how to ask this via forums or where to ask you, but as titled...

**Comment by arcadez** [comment]
You get around eh i seen ya posting about this on the neosource forum the other day :)
to quickly answer your question it will be nigh on impossible to backport all the needed code
to this older MAME core as it simply wont be compatable.

**Comment by joshsmithtogo** [comment]
Well I thought I would check with you before moving to a bigger machine build. Gonna move on past the Pi into i5 core build with just a 64 bit mame and launchbox. Thanks for letting me know though.  




Respectfully,




Joshua Smith


Mobile Email







On Fri, Feb 16, 2018 at 4:38 PM -0600, "arcadez" <notifications@github.com> wrote:












You get around eh i seen ya posting about this on the neosource forum the other day :)

to quickly answer your question it will be nigh on impossible to backport all the needed code

to this older MAME core as it simply wont be compatable.
