### ISSUE TITLE
1943: MARK II (1943mkii)

### ISSUE THREAD

**Issue by gomisensei** [arcadez/-mame2003-plus-libretro#5]
would it be possible to backport this title?  I believe it's just a clone of 1943kai

**Comment by arcadez** [comment]
Sure consider it done i already have this backported to one of my other projects, it will be
a breeze to add into this core.

**Comment by gomisensei** [comment]
can you mark the driver as not supporting save states?  my retroarch autoload/saves, but the gameplay doesn't show when state is loaded so requires a reset every time...

**Comment by arcadez** [comment]
There are no flags that can be set in MAME78 at driver level to state if a game supports
saves or not, this flag was only added to later MAME builds.
